kind: Deployment
apiVersion: apps/v1
metadata:
  name: trolley-service-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: endeavourgroup-trolley
      version: v01
  template:
    metadata:
      labels:
        app: endeavourgroup-trolley
        version: v01
    spec:
      containers:
        - name: endeavourgroup-trolley
          image: cembo/endeavourgroup_trolley:latest
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: trolley-service-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: endeavourgroup-trolley
  ports:
    - name: endeavourgroup-trolley
      protocol: TCP
      port: 80
      targetPort: 80