kind: Deployment
apiVersion: apps/v1
metadata:
  name: api-gateway-service-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: endeavourgroup-api-gateway
      version: v01
  template:
    metadata:
      labels:
        app: endeavourgroup-api-gateway
        version: v01
    spec:
      containers:
        - name: endeavourgroup-api-gateway
          image: cembo/endeavourgroup_api_gateway:latest
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: endeavourgroup-api-gateway
  ports:
    - name: endeavourgroup-api-gateway
      protocol: TCP
      port: 80
      targetPort: 80