// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trolley.Data;

#nullable disable

namespace Trolley.Migrations
{
    [DbContext(typeof(TrolleyContext))]
    [Migration("20230904010323_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Services.Trolley.Models.TrolleyProduct", b =>
                {
                    b.Property<Guid>("TrolleyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("TrolleyId", "ProductId");

                    b.ToTable("TrolleyProducts");
                });

            modelBuilder.Entity("Services.Trolley.Models.Trolley_model", b =>
                {
                    b.Property<Guid>("TrolleyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Total")
                        .HasColumnType("float");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TrolleyId");

                    b.ToTable("Trolleys");
                });

            modelBuilder.Entity("Services.Trolley.Models.TrolleyProduct", b =>
                {
                    b.HasOne("Services.Trolley.Models.Trolley_model", "Trolley")
                        .WithMany("TrolleyProducts")
                        .HasForeignKey("TrolleyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trolley");
                });

            modelBuilder.Entity("Services.Trolley.Models.Trolley_model", b =>
                {
                    b.Navigation("TrolleyProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
