// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trolley.Data;

#nullable disable

namespace Trolley.Migrations
{
    [DbContext(typeof(TrolleyContext))]
    partial class TrolleyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Services.Trolley.Models.TrolleyProduct", b =>
                {
                    b.Property<Guid>("TrolleyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("TrolleyId", "ProductId");

                    b.ToTable("TrolleyProducts");
                });

            modelBuilder.Entity("Services.Trolley.Models.Trolley_model", b =>
                {
                    b.Property<Guid>("TrolleyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Total")
                        .HasColumnType("float");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TrolleyId");

                    b.ToTable("Trolleys");
                });

            modelBuilder.Entity("Trolley.Models.TrolleyPromotion", b =>
                {
                    b.Property<int>("TrolleyPromotionTypeId")
                        .HasColumnType("int");

                    b.Property<int>("DiscountPercent")
                        .HasColumnType("int");

                    b.Property<bool>("IsOn")
                        .HasColumnType("bit");

                    b.Property<int>("PriceLevel")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("TrolleyPromotionTypeId");

                    b.ToTable("TrolleyPromotion");
                });

            modelBuilder.Entity("Trolley.Models.TrolleyPromotionType", b =>
                {
                    b.Property<int>("TrolleyPromotionTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrolleyPromotionTypeId");

                    b.ToTable("TrolleyPromotionType");
                });

            modelBuilder.Entity("Services.Trolley.Models.TrolleyProduct", b =>
                {
                    b.HasOne("Services.Trolley.Models.Trolley_model", "Trolley")
                        .WithMany("TrolleyProducts")
                        .HasForeignKey("TrolleyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trolley");
                });

            modelBuilder.Entity("Trolley.Models.TrolleyPromotionType", b =>
                {
                    b.HasOne("Trolley.Models.TrolleyPromotion", "TrolleyPromotion")
                        .WithOne("TrolleyPromotionType")
                        .HasForeignKey("Trolley.Models.TrolleyPromotionType", "TrolleyPromotionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrolleyPromotion");
                });

            modelBuilder.Entity("Services.Trolley.Models.Trolley_model", b =>
                {
                    b.Navigation("TrolleyProducts");
                });

            modelBuilder.Entity("Trolley.Models.TrolleyPromotion", b =>
                {
                    b.Navigation("TrolleyPromotionType")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
